# Default Values for kafka Connect
# This is a YAML-formatted file
# Declare variables to be passed into your templates

replicaCount: 1
kafkaConnect:
  Name: changeme
  kafkaConnectCluster: changeme-cluster
  spec:
    tasksMax: 1
    config:
      topics: changeme.topic.v1
      buffer:
        countRecords: 100
        flushTime: 120
        sizeBytes: 5000000
      session:
        timeoutMs: 900000
      consumer:
        override:
          pollIntervalMs: 90000
          pollRecords: 5
        maxPollIntervalMs: 90000
        maxPollRecords: 5
      maxPollIntervalMs: 90000
      maxPollRecords: 5
      snowflake:
        privateKey: <omitted>
        passphrase: <omitted>
        databaseName: changeMeDatabaseName
        schemaName: changeMeSchemaName
        urlName: changemeURLName
        userName: changemeUserName
        map: changemeTopicName:changemeSnowflakeTableName